### ISSUE TITLE
Ready to be checked

### ISSUE THREAD

**Issue by stigori** [Teaching-projects/SZE-FordProg-2020-Calculator2#1]
Hi Mate,

Could you please review my assignment?

**Comment by hegyhati** [comment]
Alapvetoen rendben van, szepen mukodik, de kerdes: van Neked egy jo nagy `run` fuggvenyed, ahol a szemantikai akciokat vegrehajtod. Van emogott valami megfontolas, ami miatt nem magaban a `p_` fuggvenyekben van ez megcsinalva? Szamomra sokkal logikusabbnak tunne ugy, ez a gigantikus if eleg csunyacska szegeny, illetve parhuzamosan kell maintainelni azt meg a felette levo nyelvtant is, ami elegge macera.

**Comment by stigori** [comment]
Köszi a visszajelzést.
Igazából nincsen, igyekszem javítani.

**Comment by hegyhati** [comment]
Ok, ezt rakd rendbe, aztan reszemrol rendben van az otos.

**Comment by stigori** [comment]
Commitoltam a javított verziót,
A run függvény törölve lett, így a logika az egyes p_ függvényekben került definiálsára, ahogy tanácsoltad. Emellett az output üzeneteket is formáztam picit.

**Comment by hegyhati** [comment]
:+1:
